Ext.define('SurveyApp.model.Response',{
    extend:'Ext.data.Model',
    fields:[
    {
        name:'id',
        type:'integer'
    },{
        name:'yourself',
        type:'string'
    },{
        name:'dateOfBirth',
        type:'string'
    },{
        name:'age',
        type:'string'
    },{
        name:'contract',
        type:'string'
    },{
        name:'differentOpportunity',
        type:'string'
    },{
        name:'onedisc',
        type:'string'
    },{
        name:'twodisc',
        type:'string'
    },{
        name:'threedisc',
        type:'string'
    },{
        name:'fourdisc',
        type:'string'
    },{
        name:'fivedisc',
        type:'string'
    },{
        name:'startProgramming',
        type:'string'
    },{
        name:'versionControl',
        type:'string'
    },{
        name:'keepProjects',
        type:'string'
    },{
        name:'versionurl',
        type:'string'
    },{
        name:'languages',
        type:'string'
    },{
        name:'framework',
        type:'string'
    },{
        name:'ide',
        type:'string'
    },{
        name:'level',
        type:'string'
    }],
    
});